
#Freemark 配置 prefix: classpath:/templates/#
#spring:
#  freemarker:
#    request-context-attribute: req  #req访问request
#    suffix: .html  #后缀名
#    content-type: text/html
#    enabled: true
#    cache: false #缓存配置
#    template-loader-path: classpath:/templates/
#    charset: UTF-8 #编码格式
#    settings:
#      number_format: '0.##'   #数字格式化，无小数点

#thymeleaf 配置
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache