spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springseurity?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 最大等待时间
    maxWait: 60000

    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000

    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j

    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

    druidLoginAccount: admin
    druidLoginPassword: 123456

#服务器端口配置
server:
  port: 5003

#mybatis
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true  #表字段自动映射-驼峰
    useColumnLabel: true